[project]
name = "jubilant-funicular"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.133.1",
    "fastapi-mcp>=0.4.0",
    "fastmcp>=3.0.2",
    "mcp>=1.26.0",
    "uvicorn>=0.41.0",
]
